"""create users table1

Revision ID: d38b67c0244a
Revises: 3102d548b9ef
Create Date: 2025-06-16 14:39:51.633934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38b67c0244a'
down_revision: Union[str, None] = '3102d548b9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
